services:
  db:
    image: mysql:8.0
    container_name: mysql-db
    restart: unless-stopped

    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: notes_db
      MYSQL_USER: django
      MYSQL_PASSWORD: django123

    ports:
      - "3306:3306"

  django:
    build:
      context: .
    container_name: django-app

    ports:
      - "8000:8000"

    depends_on:
      - db

    env_file:
      - .env

    restart: unless-stopped


